name: "Update Version Tags"

on:
  push:
    tags:
      - "v*.*.*"
  workflow_dispatch:
    inputs:
      tag:
        description: "Target Tag (e.g., v1.2.3)"
        required: true
        type: string

jobs:
  update-tags:
    name: "Update Tags"
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      contents: write

    steps:
      - name: "Update Tags"
        uses: cssnr/update-version-tags-action@1ff20ac5555f024f5e72b7ccdf165b867878f953 # v2.0.0
        with:
          tag: ${{ inputs.tag || github.ref_name }}
          tags: latest
